### PR TITLE
Release foreground 1.2.0

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by Hutchy68** [comment]
Will merge as soon as spelling is fixed. Would like to see #248 happen as another tester @thingles

**Comment by paladox** [comment]
@Hutchy68 ok done thanks for spotting the spelling mistake.

**Comment by Hutchy68** [comment]
Thanks! Should we follow semver, missed @kghbln comment on #242 issue. @thingles thoughts on using semver. See #253

**Comment by paladox** [comment]
Ok changed version to 1.2.0 following semver

**Comment by paladox** [comment]
Thanks

**Comment by kghbln** [comment]
:+1:

**Pull request merged**
