### PR TITLE
Fixed SkinTemplateToolboxEnd undefined

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
@Hutchy68 could you test this patch with https://github.com/thingles/foreground/pull/247 applied. I would like to see if this fixes that error.

**Comment by paladox** [comment]
Following example at

https://m.mediawiki.org/wiki/Manual:GlobalFunctions.php#wfRunHooks.28.29_example_usage

That include ''

**Comment by paladox** [comment]
This is how that hook is run in vector https://github.com/wikimedia/mediawiki-skins-Vector/blob/master/VectorTemplate.php#L273

**Comment by Hutchy68** [comment]
Thanks for this PR, it was late last night and I didn't even create an issue for it. Yes, works to fix as the notice even tells the assumption of `'SkinTemplateToolboxEnd'` not `SkinTemplateToolboxEnd`. Merging.

**Comment by paladox** [comment]
Thanks.

**Pull request merged**
