### PR TITLE
Add support for extension.json whilst supporting mw 1.24 or lower

### PR DESCRIPTION
**Pull request by paladox**
This file will only be used if you use mediawiki 1.25 or higher.

### CODE REVIEW

**Comment by Hutchy68** [comment]
This one is great! 1.23 - 1.26 compatible and fully supports 
`require_once "$IP/skins/foreground/foreground.php";` in 1.23.x
and 
`wfLoadSkin( 'foreground' );` in 1.26

All Foreground feature parameters are still working. Also tested default skin usage and everything else I could think of. A big :+1: for making Foreground 1.26 compatible as well as backwards compatible as I also tested it on a 1.23.11.

Load times on my test wiki with Firefox using 1.26 showed about 3 to 4 secs on a first load or hard reload. On a browsing or reloading pages, etc. down to 1 to 1.3 secs.

**Comment by paladox** [comment]
Thanks.

This https://github.com/thingles/foreground/pull/238 should be merged first then this. Since this includes position top.

**Comment by paladox** [comment]
Thanks.

**Comment by paladox** [comment]
This is ready to merge now.

**Comment by Hutchy68** [comment]
Ok, this is totally bizarre. I see a very slight improvement with 1.23, but 1.26 it actually increases the load time. The performance gains aren't coming from the point the DOM is actually finished. Yes, 1.26 DOM load is really fast beating 1.23 by a full second, but 1.26 is now lagging a lot more with the rest of the modules loading. The original method was async anyway from the top position. 

I think I even have more extensions for testing on the 1.23 site. 1.26 is pretty vanilla, with about 8 out of the box extensions.

**Comment by paladox** [comment]
Should I make js module position top too.

**Comment by Hutchy68** [comment]
I hate to say it but I think so.  Going forward the concentration will be more on 1.26 and later. Wish there was more documentation on exactly how the module loader is working now.

**Comment by paladox** [comment]
Ok done.

**Comment by paladox** [comment]
Thanks.

**Pull request merged**
