### PR TITLE
Remove I18n shim

### PR DESCRIPTION
**Pull request by kghbln**
Since v2.0.1 requires 1.25+ we can remove the shim required for < MW1.23

Refs: https://github.com/thingles/foreground/issues/287

### CODE REVIEW

**Comment by kghbln** [comment]
@Hutchy68 A squash and merge will be nice. :)

**Comment by Hutchy68** [comment]
You can basically remove almost everything from `foreground.php` not just the message registration. Here is the boilerplate.

```
<?php
if ( function_exists( 'wfLoadSkin' ) ) {
	wfLoadSkin( 'FooBar' );
	// Keep i18n globals so mergeMessageFileList.php doesn't break
	$wgMessagesDirs['FooBar'] = __DIR__ . '/i18n';
	wfWarn(
		'Deprecated PHP entry point used for FooBar skin. Please use wfLoadSkin instead, ' .
		'see https://www.mediawiki.org/wiki/Extension_registration for more details.'
	);
	return;
} else {
	die( 'This version of the FooBar skin requires MediaWiki 1.25+' );
}
```

The rest of the file isn't necessary because everything is automagically loaded 😄 from the `skin.json` file.

**Comment by kghbln** [comment]
With the shim I only broke for < MW 1.23 but now I get why you chose MW 1.25, not just page indicator support.

**Comment by kghbln** [comment]
New pull: https://github.com/thingles/foreground/pull/294

**Pull request closed without merging**
