### PR TITLE
Update foreground.css

### PR DESCRIPTION
**Pull request by kghbln**
Make the "preview" button appear as the "save page" and "show changes" button

### CODE REVIEW

**Comment by kghbln** [comment]
@Hutchy68 I never understood why there is a difference

**Comment by kghbln** [comment]
@Hutchy68 I will do a fresh pull request if such  a change is acceptable. I also need to add a fix for WikiEditor like the one I did for Pivot.

**Comment by Hutchy68** [comment]
👍

**Comment by kghbln** [comment]
Now https://github.com/thingles/foreground/pull/292

**Pull request closed without merging**
