### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by paladox**
By splitting them it improves performance.

All tested.

I carn't be hundread percent sure it will improve the performance but on my very slow site it loads a bit fastster.

### CODE REVIEW

**Comment by Hutchy68** [comment]
Is this one building on patch-14? By itself it breaks the skin, no css or js is loading.

**Comment by paladox** [comment]
I think it is. Ive tested this and works.

**Comment by paladox** [comment]
I will merge this into https://github.com/thingles/foreground/pull/236

**Comment by Hutchy68** [comment]
Did you update the json file? I think that might have been what was causing the issue because you reference the top in json but no bottom for the js files and I was testing this on 1.26.

**Comment by paladox** [comment]
Yes.

**Pull request closed without merging**
