### PR TITLE
Update Foreground in foundation 5 branch

### PR DESCRIPTION
**Pull request by paladox**
Updates to match some of the changes in develop branch.

### CODE REVIEW

**Comment by paladox2015** [comment]
@Hutchy68

**Comment by Hutchy68** [comment]
Thanks @paladox

**Comment by paladox** [comment]
Hi should I open another pull request since there is another update to foundation 5 @Hutchy68

**Comment by Hutchy68** [comment]
Yes, please do. I meant to ping you and ask if you had time. There's also another PR against 1.1 which fixes a h tag element. Feel free to roll that in to,  I think it's only a CSS change.  A line or two. Thanks @paladox

**Comment by paladox** [comment]
Ok will do.

**Comment by paladox** [comment]
Should I also do a pull to add missing indicator.gif file in the develop branch.

**Comment by paladox** [comment]
Do you mind if I update some of the code in foreground.css since some is outdated and some code uses code that was in mediawiki but was either changed or was removed. this update will probley not work with certain mediawiki versions.

**Comment by paladox** [comment]
Also I will try out less because less and css work together and css can also be used in a less file.

**Comment by paladox** [comment]
@Hutchy68

**Comment by Hutchy68** [comment]
I think we need to have a discussion abt what versions of MW will v2 support when released. The more the better. Greater use, more testing, quicker to release if we cap at 1.23.x.  I think in my mind I consider all the non-LTS versions of MW  development versions. What may be in one maintenance release might not be in the next one or the one after.  If you do a lot of classwork there's no guarantee that it won't change again a few maintenance releases down the road. Then we are stuck having to fix something that will work with a finite amount of maintenance versions. 

If we concentrate on 1.19/1.23 and push out v2 then we can start 1.24 stuff in the development branch. Once foundation 5 branch is ready I'll roll that into the current development branch and delete the foundation 5 branch.  Fixes for v1.1 can still be patched against relase/1.1 branch.

**Comment by paladox** [comment]
less is supported by MediaWiki 1.22 or higher.

**Comment by paladox** [comment]
I have made some changes to the title at top since the hide code in the css did not work because code in the template was not there I added it but made some changes.

**Pull request merged**
