### PR TITLE
Clean update to Foundation 5 from develop branch as a base

### PR DESCRIPTION
**Pull request by Hutchy68**
**OK to Merge**

Sometimes it is better to backup and start fresh. This is a **clean and working** update to Foundation 5 off of the current develop branch as its base. A couple things to note:

1. <strike>I have disabled on hover for the 'Actions' button for now in foreground.js</strike> **This has been re-enabled**
2. There was a regression in Foundation 5 with pip (triangle) alignment and dropdown alignment which Foundation claims is fixed in 5.5.x. Apparently not out of the box, I found references to "there needs to be an additional parent div" to correct the detection. Note on a base click of Actions, the dropdown always goes right. **NO Fix, Foundation 6 development started and is now released so the fix never was 100% fixed. Moved bottom dropdown to left dropdown. The native on hover works much better even though it isn't a bottom dropdown.**
3. Tabs feature was not included. Need to look at that a bit more closely, the `ob_cache, ob_flush` et al was causing issues and I'm not sure why it was even being used.
4.  <strike>Search is fixed mostly, but the break point of large to small is now narrower for screen width. Search reacts to the new break point of medium. Medium is more predominant in 5.x.x so we need to look at what break point makes us comfortable. The left menus will definitely be affected by the new break point and the top bar will stack with ugliness.</strike> **Solved with auto height until break point for small screens. Left and right top-bars now flow and stack.**

Could be a couple more things I missed, but so far the above is what I noticed right off.

### CODE REVIEW

**Comment by paladox** [comment]
@Hutchy68 Seems that the echo problem is back. I have a fix waiting to be pushed the pull that updates the foundation branch. When echo updated there styles they added a check to make sure it was vector. Meaning we have to include those style files directly now.

**Comment by Hutchy68** [comment]
I can't confirm that, echo seems to be working fine for me in 1.26.  I'm using the version of echo I downloaded 5 days ago for v1.26.

**Comment by paladox** [comment]
Ok. Then Echo isen't working for mw 1.27.

In the patch ive uploaded I kept backword compatible. With the update I added two less files for echo in skin.json but not in foreground.php since mw 1.24 whould work perfectly. 

I also kept a deprecated hook so if someone using for example mw 1.26 then the new hook is used if someone for example used 1.24 then the old hook would be used.

**Comment by Hutchy68** [comment]
What is not working? I just tried Echo master with 1.26 and it works, but needs a tweak to CSS, two lines. A quick look and the .less files for vector and monobook were just there to custom style by skin, however in a step in the right direction they also have the .less files to load with their extension in a vanilla format, not skin specific. That's a big plus, so why do you think we need to grab Vector styles?

**Comment by thingles** [comment]
@Hutchy68 wow — echo is finally considering other skins!? That's a great step for that extension!

**Comment by Hutchy68** [comment]
I just took a quick look through the commits and It looks like the only check for a skin specific style is to figure out what skin. All the base styles aren't skin specific, they are vanilla and loaded first.  The only break I saw with the new echo using the master branch was the background color of the notif rectangle. That's because the target changed a tad bit.

**Comment by paladox** [comment]
Yes echo showed and worked but the colour for the background wasn't.

**Comment by Hutchy68** [comment]
Probably they are missing that class from the default load  of course it's easy to do when the class name itself is .something-absolutely-ridiculously-popup-and-long-ui-because-someone-is-not-taking-the-time  to actually look at what's the best way to class this out.

**Comment by paladox** [comment]
Ok.

**Comment by Hutchy68** [comment]
# 4 might have a solution, stack using hide classes

mediumsolution

**Comment by paladox** [comment]
This change here https://github.com/thingles/foreground/pull/270 fixes the drop down so you can use it properly in foundation 5. I also merged some off your changes here. I am not sure which one you would like to review

**Pull request merged**
