### PR TITLE
Updating foundation to 5.5.1

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
This has two new files. also includes some changes please revert them if they cause more problems.

**Comment by paladox** [comment]
It seems that when hovering the drop downs do not show you have to click manualy. also search bar btton to the right is out of place. and also some navigation boxes at top do not show hover colour or are shown different colours.

**Comment by paladox** [comment]
@Hutchy68 please review.

**Comment by Hutchy68** [comment]
I'll try it tomorrow. What versions is this compatible with?

**Comment by paladox** [comment]
This should be same compatibility I think. Not sure though. But I tested it with mediawiki 1.26 which should work with 1.25 and 1.24.

**Comment by thingles** [comment]
I don't feel ready to move to Foundation 5, there are a number of breaking changes and this PR doesn't indicate how those are resolved or prove the PR is functional.

**Comment by thingles** [comment]
Sorry, I didn’t notice this was on the foundation5 branch. Fine, will merge.

**Pull request merged**
