### PR TITLE
Drop support for < MW 1.25

### PR DESCRIPTION
**Pull request by kghbln**
Since v2.1.0 requires 1.25+ we can remove the shim required for < MW1.23 and the classic invocation for < MW 1.25

Refs: https://github.com/thingles/foreground/issues/287

### CODE REVIEW

**Comment by kghbln** [comment]
@Hutchy68 Enhanced version of https://github.com/thingles/foreground/pull/291

As always: Squash and merge. :)

**Comment by Hutchy68** [comment]
Thanks @kghbln 

You can still use the `require_once "$IP/skins/foreground/foreground.php";` statement but it will generate the Deprecated Message in the logs if logging is enabled. Or if someone is using the development output. Anyway, best to point at the proper `wfLoadSkin` statement only.

Thanks again!

**Comment by kghbln** [comment]
> You can still use the require_once "$IP/skins/foreground/foreground.php";

Indeed which make migration easier on upgrading and new installs should use `wfLoadSkin`. That's why I removed the line in the README.

**Comment by kghbln** [comment]
This Extension Loading shim can be removed at another point in time.

**Pull request merged**
